import { LandingImagesProduct } from "@/constants/img.constants";

export const LandingPageContent: ProductListLandingProps[] = [
  {
    src: LandingImagesProduct.kid10,
    alt: "product image",
    title: "Nike sport wear classic",
    description: "A stylish and comfortable sport wear for kids.",
    price: "$150.00",
    category: "kids wear",
    link: "/product/nike-sport-wear-classic",
  },
  {
    src: LandingImagesProduct.kid11,
    alt: "product image",
    title: "Adidas classic shoes",
    description: "A stylish and comfortable classic shoes for kids.",
    price: "$100.00",
    category: "kids wear",
    link: "/product/adidas-classic-shoes",
  },
  {
    src: LandingImagesProduct.kid12,
    alt: "product image",
    title: "Puma classic shoes",
    description: "A stylish and comfortable classic shoes for kids.",
    price: "$80.00",
    category: "kids wear",
    link: "/product/puma-classic-shoes",
  },
  {
    src: LandingImagesProduct.kid9,
    alt: "product image",
    title: "Reebok classic shoes",
    description: "A stylish and comfortable classic shoes for kids.",
    price: "$120.00",
    category: "kids wear",
    link: "/product/reebok-classic-shoes",
  },
  {
    src: LandingImagesProduct.Kid8,
    alt: "product image",
    title: "Converse classic shoes",
    description: "A stylish and comfortable classic shoes for kids.",
    price: "$90.00",
    category: "kids wear",
    link: "/product/converse-classic-shoes",
  },
  {
    src: LandingImagesProduct.Kid7,
    alt: "product image",
    title: "Adidas classic shoes",
    description: "A stylish and comfortable classic shoes for kids.",
    price: "$100.00",
    category: "kids wear",
    link: "/product/adidas-classic-shoes",
  },
  {
    src: LandingImagesProduct.Kid6,
    alt: "product image",
    title: "Puma classic shoes",
    description: "A stylish and comfortable classic shoes for kids.",
    price: "$80.00",
    category: "kids wear",
    link: "/product/puma-classic-shoes",
  },
  {
    src: LandingImagesProduct.Kid5,
    alt: "product image",
    title: "Reebok classic shoes",
    description: "A stylish and comfortable classic shoes for kids.",
    price: "$120.00",
    link: "/product/reebok-classic-shoes",
    category: "kids wear",
  },
  {
    src: LandingImagesProduct.Kid4a,
    alt: "product image",
    title: "Converse classic shoes",
    description: "A stylish and comfortable classic shoes for kids.",
    price: "$90.00",
    category: "kids wear",
    link: "/product/converse-classic-shoes",
  },
  {
    src: LandingImagesProduct.Kid3a,
    alt: "product image",
    title: "Nike sport wear classic",
    description: "A stylish and comfortable sport wear for kids.",
    price: "$150.00",
    category: "kids wear",
    link: "/product/nike-sport-wear-classic",
  },
  {
    src: LandingImagesProduct.Kid2a,
    alt: "product image",
    title: "Adidas classic shoes",
    description: "A stylish and comfortable classic shoes for kids.",
    price: "$100.00",
    category: "kids wear",
    link: "/product/adidas-classic-shoes",
  },
  {
    src: LandingImagesProduct.Kid1a,
    alt: "product image",
    title: "Puma classic shoes",
    description: "A stylish and comfortable classic shoes for kids.",
    price: "$80.00",
    category: "kids wear",
    link: "/product/puma-classic-shoes",
  },
];
